### ISSUE TITLE
REQUEST: Guide to setup this project on my machine.

### ISSUE THREAD

**Issue by Ankitkj1999** [AV-Studios/SRMOne#34]
I am new to this project and am currently learning flutter and firebase integration. But I would like to work on this SRMOne app. The issue that I am currently facing is I am not able to set up this project for myself.  Although the code itself is working the app is missing full functionality, which is due to the reason I haven't integrated firebase or google signing with it.  

It would be really helpful for me if I  can get a guide on how to set up this projects and integrate with firebase.

**Comment by adityathakurxd** [comment]
Hi @Ankitkj1999!
Sorry for the late reply on this. I missed out on adding an assignment to the workflow and never saw this issue until today. We are taking this project as an on-campus thing at SRM, Delhi and wouldn't probably have external contributors for a bit.

Really sorry for this late ping! But, have a great week ahead with the Diwali festivities. Cheers!
